package com.example.flashcard.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006d33)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF91f9ab)
val md_theme_light_onPrimaryContainer = Color(0xFF00210a)
val md_theme_light_secondary = Color(0xFF506352)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFd3e8d3)
val md_theme_light_onSecondaryContainer = Color(0xFF0e1f12)
val md_theme_light_tertiary = Color(0xFF00696f)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFF6ff6fe)
val md_theme_light_onTertiaryContainer = Color(0xFF002022)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfbfdf7)
val md_theme_light_onBackground = Color(0xFF1a1c19)
val md_theme_light_surface = Color(0xFFfbfdf7)
val md_theme_light_onSurface = Color(0xFF1a1c19)
val md_theme_light_surfaceVariant = Color(0xFFdde4da)
val md_theme_light_outline = Color(0xFF727971)
val md_theme_light_inverseOnSurface = Color(0xFFf0f2ec)
val md_theme_light_inverseSurface = Color(0xFF2f312e)

val md_theme_dark_primary = Color(0xFF74db90)
val md_theme_dark_onPrimary = Color(0xFF003917)
val md_theme_dark_primaryContainer = Color(0xFF005225)
val md_theme_dark_onPrimaryContainer = Color(0xFF91f9ab)
val md_theme_dark_secondary = Color(0xFFb7ccb7)
val md_theme_dark_onSecondary = Color(0xFF233426)
val md_theme_dark_secondaryContainer = Color(0xFF384b3b)
val md_theme_dark_onSecondaryContainer = Color(0xFFd3e8d3)
val md_theme_dark_tertiary = Color(0xFF4cd9e2)
val md_theme_dark_onTertiary = Color(0xFF00363a)
val md_theme_dark_tertiaryContainer = Color(0xFF004f54)
val md_theme_dark_onTertiaryContainer = Color(0xFF6ff6fe)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1a1c19)
val md_theme_dark_onBackground = Color(0xFFe2e3de)
val md_theme_dark_surface = Color(0xFF1a1c19)
val md_theme_dark_onSurface = Color(0xFFe2e3de)
val md_theme_dark_surfaceVariant = Color(0xFF414941)
val md_theme_dark_onSurfaceVariant = Color(0xFFc1c9bf)
val md_theme_dark_outline = Color(0xFF8b938a)
val md_theme_dark_inverseOnSurface = Color(0xFF1a1c19)
val md_theme_dark_inverseSurface = Color(0xFFe2e3de)

val seed = Color(0xFF008040)
val error = Color(0xFFba1b1b)